version: "3.9"

services:
  django:
    build: ./api
    container_name: weather_backend
    env_file:
      - .env
    volumes:
      - ./api:/app:rw
      - /home/pi/weather_logs:/app/logs:rw
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    build: ./nginx
    container_name: weather_nginx
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - /home/pi/weather_logs:/app/logs