version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather_backend
    command: gunicorn weather.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - /home/admin/weather_logs:/app/logs/weather
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: weather_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - django

volumes:
  static_volume: